// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "strconv"

const TableNameUser = "admin_user"

// User mapped from table <user>
type AdminUser struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name;not null;comment:用户名称" json:"name"`         // 用户名称
	Mobile    string         `gorm:"column:mobile;not null;comment:用户手机号" json:"mobile"`    // 用户手机号
	Password  string         `gorm:"column:password;not null;comment:用户密码" json:"password"` // 用户密码
	Level  uint         `gorm:"column:level;not null;comment:用户密码" json:"level"` // 等级
	CreatedAt int64 `gorm:"autoCreateTime"`      // 使用时间戳秒数填充创建时间
	UpdatedAt int64 `gorm:"autoUpdateTime"` // 使用时间戳毫秒数填充更新时间
	//DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName User's table name
func (*AdminUser) TableName() string {
	return TableNameUser
}

func (user AdminUser) GetUid() string {
	return strconv.Itoa(int(user.ID))
}


