// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameRoute = "route"

type Meta struct {
	Icon       string `xsql:"icon json:"icon"" `
	Title      string `xsql:"title" json:"title"`
	AlwaysShow bool   `xsql:"alwaysShow json:"alwaysShow"`
}

// Route mapped from table <route>
type Route struct {
	ID        uint  `gorm:"column:id;primaryKey;autoIncrement:true" xsql:"id" json:"id"`
	Path      string `gorm:"column:path;not null" xsql:"path" json:"path"`
	Component string `gorm:"column:component" xsql:"component" json:"component"`
	Redirect  string `gorm:"column:redirect" xsql:"redirect" json:"redirect"`
	Name      string `gorm:"column:name;not null" xsql:"name" json:"name"`
	ParentID uint    `gorm:"column:parent_id" xsql:"parent_id" json:"parent_id"`
	Parent   *Route  `gorm:"-" xsql:"parent" json:"parent"`
	Children []Route `gorm:"-"  xsql:"children" json:"children"`
	MetaStr  string  `gorm:"column:meta" xsql:"meta" json:"metaStr"`
	Meta     Meta    `gorm:"-" xsql:"" json:"meta"`
}

// TableName Route's table name
func (*Route) TableName() string {
	return TableNameRoute
}
